"""Weekly nutrition plan view."""

import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from dotenv import load_dotenv
load_dotenv(ROOT / ".env")

import streamlit as st
import altair as alt
import pandas as pd
from datetime import date, timedelta

from dashboard.lib import airtable_client as db

st.set_page_config(page_title="Nutrition · Hyrox Coach", page_icon="🥗", layout="wide")
st.title("🥗 Nutrition Plan")

# ── Week selector ──────────────────────────────────────────────────────────────
today = date.today()
this_monday = today - timedelta(days=today.weekday())

week_offset = st.select_slider(
    "Week",
    options=[-1, 0, 1],
    value=0,
    format_func=lambda x: {-1: "Last week", 0: "This week", 1: "Next week"}[x],
)
week_start = this_monday + timedelta(weeks=week_offset)
week_end   = week_start + timedelta(days=6)

st.caption(f"📅 {week_start.strftime('%d %b')} — {week_end.strftime('%d %b %Y')}")

if st.button("🔄 Refresh"):
    db.get_nutrition_plans.clear()
    st.rerun()

# ── Load nutrition data ────────────────────────────────────────────────────────
nutrition = db.get_nutrition_plans(week_start.isoformat(), week_end.isoformat())
sessions  = db.get_training_sessions(week_start.isoformat(), week_end.isoformat())

if not nutrition:
    st.info(
        "No nutrition data found for this week.\n\n"
        "Nutrition plans are generated by **Workflow E** (Weekly Plan Generator) "
        "and stored in Airtable. Run Workflow E to populate this view."
    )
    st.divider()
    st.subheader("📊 Caloric targets by session type")
    st.markdown("""
| Session type | Caloric target | Carbs |
|---|---|---|
| Rest / Mobility | 1900–2200 kcal | 2–3 g/kg |
| Active recovery / easy Z2 <45 min | 2100–2400 kcal | 2–3 g/kg |
| Z2 endurance / Strength (moderate) | 2400–2700 kcal | 3–5 g/kg |
| Intervals / Long run / Hyrox simulation | 2700–3100 kcal | 5–7 g/kg |

Protein stays constant at **1.8–2.2 g/kg** regardless of session type.
""")
    st.stop()

# ── Macro summary chart ────────────────────────────────────────────────────────
df = pd.DataFrame(nutrition)
df["date"] = pd.to_datetime(df["date"]).dt.date
df = df.sort_values("date")

st.subheader("📊 Weekly macro overview")
c1, c2 = st.columns(2)

with c1:
    if "calories" in df.columns:
        chart = (
            alt.Chart(df)
            .mark_bar(color="#e74c3c", cornerRadiusTopLeft=4, cornerRadiusTopRight=4)
            .encode(
                x=alt.X("date:T", title="Date", axis=alt.Axis(format="%a %d")),
                y=alt.Y("calories:Q", title="Calories (kcal)"),
                tooltip=["date:T", "calories:Q"],
            )
            .properties(title="Daily Calories", height=250)
        )
        st.altair_chart(chart, use_container_width=True)

with c2:
    macro_cols = [c for c in ["protein_g", "carbs_g", "fat_g"] if c in df.columns]
    if macro_cols:
        df_melted = df.melt(id_vars=["date"], value_vars=macro_cols, var_name="macro", value_name="grams")
        df_melted["macro"] = df_melted["macro"].map({"protein_g": "Protein", "carbs_g": "Carbs", "fat_g": "Fat"})
        chart2 = (
            alt.Chart(df_melted)
            .mark_bar()
            .encode(
                x=alt.X("date:T", title="Date", axis=alt.Axis(format="%a %d")),
                y=alt.Y("grams:Q", title="Grams"),
                color=alt.Color("macro:N", scale=alt.Scale(
                    domain=["Protein", "Carbs", "Fat"],
                    range=["#3498db", "#f39c12", "#2ecc71"],
                )),
                tooltip=["date:T", "macro:N", "grams:Q"],
            )
            .properties(title="Macros (g)", height=250)
        )
        st.altair_chart(chart2, use_container_width=True)

# ── Day-by-day meal plans ──────────────────────────────────────────────────────
st.divider()
st.subheader("🍽️ Day-by-day meal plans")

for i in range(7):
    day = week_start + timedelta(days=i)
    plan = next((n for n in nutrition if str(n.get("date",""))[:10] == day.isoformat()), None)
    session = next((s for s in sessions if s.get("date","")[:10] == day.isoformat()), None)
    is_today = day == today

    with st.expander(
        f"{day.strftime('%A %d %B')}"
        + (f" — {plan.get('calories','?')} kcal" if plan else ""),
        expanded=is_today,
    ):
        if plan:
            col_a, col_b = st.columns([3, 1])
            with col_b:
                st.metric("Calories", f"{plan.get('calories','?')} kcal")
                st.metric("Protein", f"{plan.get('protein_g','?')} g")
                st.metric("Carbs",   f"{plan.get('carbs_g','?')} g")
                st.metric("Fat",     f"{plan.get('fat_g','?')} g")
                if session:
                    st.caption(f"🏋️ {session.get('session_type','?')}")
            with col_a:
                meals_raw = plan.get("meals", "")
                if meals_raw:
                    for slot in meals_raw.split(" / "):
                        slot = slot.strip()
                        if slot:
                            if ":" in slot:
                                label, content = slot.split(":", 1)
                                st.markdown(f"**{label.strip()}:** {content.strip()}")
                            else:
                                st.markdown(slot)
                else:
                    st.caption("No meal details available.")

                groceries_raw = plan.get("daily_groceries", "")
                if groceries_raw:
                    st.divider()
                    st.markdown("**🛒 Shopping list for today**")
                    items = [i.strip() for i in groceries_raw.split("\n") if i.strip()]
                    cols = st.columns(2)
                    for idx, item in enumerate(items):
                        cols[idx % 2].markdown(f"- {item}")
        else:
            st.caption("No nutrition data for this day.")
